name = "PowerFlowLimits"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PowerFlowLimits", "qpf-check"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "PowerFlowLimits"

[[lean_lib]]
name = "Challenge"

[[lean_exe]]
name = "qpf-check"
root = "PowerFlowLimits.Certificate.Main"
